#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-awxkit
Version  : 19.4.0
Release  : 13
URL      : https://files.pythonhosted.org/packages/ee/77/b792fb011c63efbe37bcd78b700d039d95ce57ebcfedea3fd8b219347574/awxkit-19.4.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/ee/77/b792fb011c63efbe37bcd78b700d039d95ce57ebcfedea3fd8b219347574/awxkit-19.4.0.tar.gz
Summary  : The official command line interface for Ansible AWX
Group    : Development/Tools
License  : Apache-2.0
Requires: pypi-awxkit-bin = %{version}-%{release}
Requires: pypi-awxkit-python = %{version}-%{release}
Requires: pypi-awxkit-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(pyyaml)
BuildRequires : pypi(requests)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
awxkit
======
Python library that backs the provided `awx` command line client.
For more information on installing the CLI and building the docs on how to use it, look [here](./awxkit/cli/docs).

%package bin
Summary: bin components for the pypi-awxkit package.
Group: Binaries

%description bin
bin components for the pypi-awxkit package.


%package python
Summary: python components for the pypi-awxkit package.
Group: Default
Requires: pypi-awxkit-python3 = %{version}-%{release}

%description python
python components for the pypi-awxkit package.


%package python3
Summary: python3 components for the pypi-awxkit package.
Group: Default
Requires: python3-core
Provides: pypi(awxkit)
Requires: pypi(pyyaml)
Requires: pypi(requests)

%description python3
python3 components for the pypi-awxkit package.


%prep
%setup -q -n awxkit-19.4.0
cd %{_builddir}/awxkit-19.4.0
pushd ..
cp -a awxkit-19.4.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1672257425
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 setup.py build

popd
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -tt setup.py build install --root=%{buildroot}-v3
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/akit
/usr/bin/awx

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
